# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6afcf3c55a2dad4ef5d849e3eb287c166c77284142762b9c8681771e96644ff0baa4b50947e35aafd5b5c8b3a43a411f20b627e677e90ad61ddd00f86e8268a

test:
  secret_key_base: 7be2a61afc71c9088d3bf29320a1442205e96789cc04d6493859088de6976cb2f40f2f30322eab73b0795ab1fe917bb06bde10283734b57f2131b82c7f037073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
